menu:
- {name: 'people', url: '/people'}
- {name: 'expertise', url: '/expertise'}
- {name: 'services', url: '/services'}
- {name: 'projects', url: '/projects'}
- {name: 'contact', url: '/contact'}

people:
- name: Kambiz Homayounfar
  title: Our founder
  image: assets/img/kambiz.jpg
  url: kambiz-homayounfar
  description: >
    With over 30 years in the tech industry, Kambiz Homayounfar has thrived in technology-focused ventures, private equity, and M&A.
    His notable clients include major corporations like IBM, Microsoft, NTT Docomo, and Toyota, among others.
    Kambiz successfully founded and expanded companies such as Phybit, Genista Corporation, and Algorex, which were subsequently acquired.
    Throughout his career, he has occupied pivotal roles at Teknekron and Asahi Chemical.
    Kambiz obtained his degree in Computational Electronics from the University of Cardiff and pursued postgraduate studies in Electrical Engineering at Rensselaer Polytechnic Institute.

social:
- {icon: 'github', link: 'https://github.com/algotechniq'}
# - {icon: 'twitter', link: 'https://twitter.com/algotechniq'}
# - {icon: 'instagram', link: 'https://instagram.com/algotechniq'}
- {icon: 'linkedin', link: 'https://jp.linkedin.com/in/kambiz-homayounfar-b379a01ba'}

contacts:
- name: 'Algotechniq LLC'
  title: 'Address'
  department: 'Ebisu 2-28-10'
  institution: 'Shibuya-ku'
  institution_address: 'Tokyo 150-0013, Japan'
  office: 'Shu Building 2982'
  phone: '(070) 8902-8057'
  email: 'mos@algotechniq.com'
  image: 'assets/img/contact.jpg'
